/**
 * SQL lấy nguyên văn từ site/jsp/Common/dashboard/dashboard_*.jsp trong repo `pimsvina`
 * (d:\code\pimsvina) — dùng để query thẳng Oracle (PIMSVINA) thay vì gọi REST + JWT qua Tomcat.
 * Mỗi lần đồng bộ SQL phía JSP, phải copy lại đúng nguyên văn vào đây để tránh lệch dữ liệu.
 */

function currentYYYYMM(): string {
  const d = new Date();
  return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export interface OracleEndpointQuery {
  sql: string;
  /** node-oracledb dùng named bind (:name), khác với `?` JDBC gốc trong JSP. */
  binds?: (params: Record<string, string>) => Record<string, unknown>;
}

export const ORACLE_DASHBOARD_QUERIES: Record<string, OracleEndpointQuery> = {
  "dashboard_pd_overview_1q.jsp": {
    sql: `SELECT
        A.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = A.FLDCODE) AS SITE_CODE,
        A.FLDNAME AS PROJECT_NAME,
        NVL(CT.TOTALCTRTWONAMT, NVL(CT.TOTALCTRTUSDAMT, UT.CTRTAMT)) AS CONTRACT_AMOUNT,
        CASE WHEN LENGTH(NVL(CP.CTRTSTDATE, UT.CTRTSTDATE)) = 8 THEN SUBSTR(NVL(CP.CTRTSTDATE, UT.CTRTSTDATE), 1, 4) || '-' || SUBSTR(NVL(CP.CTRTSTDATE, UT.CTRTSTDATE), 5, 2) || '-' || SUBSTR(NVL(CP.CTRTSTDATE, UT.CTRTSTDATE), 7, 2) ELSE NVL(CP.CTRTSTDATE, UT.CTRTSTDATE) END AS START_DATE,
        CASE WHEN LENGTH(NVL(CP.CTRTEDDATE, UT.CTRTEDDATE)) = 8 THEN SUBSTR(NVL(CP.CTRTEDDATE, UT.CTRTEDDATE), 1, 4) || '-' || SUBSTR(NVL(CP.CTRTEDDATE, UT.CTRTEDDATE), 5, 2) || '-' || SUBSTR(NVL(CP.CTRTEDDATE, UT.CTRTEDDATE), 7, 2) ELSE NVL(CP.CTRTEDDATE, UT.CTRTEDDATE) END AS END_DATE,
        (SELECT TT.ORDERCONAME FROM (
            SELECT RANK() OVER (ORDER BY NVL(X.REPYNDVS,'0')||NVL(Y.CUSTNAME,' ') DESC) AS RNK,
                   NVL(Y.CUSTNAME, NVL(X.ORDERCORPCODE,''))
                   || CASE WHEN COUNT(0) OVER (PARTITION BY 0) = 1 THEN ''
                           ELSE ' AND ' || TO_CHAR(COUNT(0) OVER (PARTITION BY 0) - 1) || ' COMPANIES' END AS ORDERCONAME
            FROM CBTB_ORDERCORP X
            LEFT OUTER JOIN IFTB_CUSTMST Y ON X.ORDERCORPCODE = Y.CUSTCODE
            WHERE X.FLDCODE = A.FLDCODE
        ) TT WHERE TT.RNK = 1
        ) AS CLIENT,
        CAST(NULL AS VARCHAR2(100)) AS SCALE,
        TO_CHAR(SYSDATE, 'YYYYMM')   AS AS_OF_MONTH,
        CAST(NULL AS VARCHAR2(100)) AS SCOPE,
        (SELECT SUM(P.PLAN1 + P.PLAN2 + P.PLAN3 + P.PLAN4 + P.PLAN5 + P.PLAN6 + P.PLAN7 + P.PLAN8 + P.PLAN9 + P.PLAN10 + P.PLAN11 + P.PLAN12)
         FROM CJTB_BUSPLAN_DETL P
         WHERE P.FLDCODE = A.FLDCODE
        ) AS REVENUE_ANNUAL_TARGET,
        (SELECT SUM(S.PROGSALESAMT) FROM CJTB_SALESAMTRST S
         WHERE S.FLDCODE = A.FLDCODE
        ) AS REVENUE_TOTAL,
        (SELECT SUM(SCHDAMT) FROM CCTB_UTKSCHD
         WHERE FLDCODE = A.FLDCODE AND SCHDTYPECODE = '1' AND APPRSTSCODE = '40'
        ) AS CASH_CONFIRMED,
        (SELECT SUM(ROUND(X.AMOUNT / NULLIF((SELECT MAX(R.CHGRATIO) KEEP (DENSE_RANK LAST ORDER BY R.YYMM) FROM CHTB_EXCHANGE_RATIO R WHERE R.EXCHANGE_TYPE = '.' AND R.BASEMONEY = 'VND' AND R.CHGMONEY = 'USD' AND R.YYMM <= SUBSTR(X.TRANSACTIONDATE, 1, 6)), 0), 2))
         FROM CFTB_CFTRANSACTION X
         JOIN CFTB_CASHFLOWTYPE T ON (T.CASHFLOWTYPECODE = X.CASHFLOWTYPE OR T.CASHFLOWTYPENAME = X.CASHFLOWTYPENAME)
         JOIN CATB_COMPANYSTRUCT_PROJECT P ON P.COMPCODE = X.COMPANY AND P.FLDCODE = X.SITE AND NVL(P.USEYN, 'Y') = 'Y'
         JOIN CATB_BUSILINE BL ON BL.BUSILINECODE = P.BUSILINECODE
         WHERE X.SITE = A.FLDCODE AND X.DEPOSITWITHDRAWAL = 'Income'
           AND UPPER(NVL(T.DISPLAYCASHFLOWREPORT, 'BUSILINE')) IN ('BUSILINE', 'BOTH')
           AND UPPER(NVL(BL.CLASSIFICATION, '')) IN ('SITE', 'BUSILINE')
        ) AS CASH_COLLECTION
    FROM CBTB_FLDSUMM A
    LEFT JOIN CBTB_CTRTSUMM CT ON CT.FLDCODE = A.FLDCODE
    LEFT JOIN (SELECT FLDCODE, CTRTSTDATE, CTRTEDDATE FROM CBTB_CONSTPERIOD P
               WHERE CHGSEQ = (SELECT MAX(CHGSEQ) FROM CBTB_CONSTPERIOD WHERE FLDCODE = P.FLDCODE)) CP ON CP.FLDCODE = A.FLDCODE
    LEFT JOIN (SELECT FLDCODE, CTRTAMT, CTRTSTDATE, CTRTEDDATE FROM CCTB_UTKCHGSEQ U
               WHERE UTKCHGSEQ = (SELECT MAX(UTKCHGSEQ) FROM CCTB_UTKCHGSEQ WHERE FLDCODE = U.FLDCODE)) UT ON UT.FLDCODE = A.FLDCODE
    ORDER BY A.FLDNAME`,
  },

  "dashboard_pd_progress_1q.jsp": {
    // STNDCLSCODE 'ZAA%' là tiền tố SAI (không có bản ghi nào khớp trong CHTB_PFMCOSTRMRK - xem comment
    // chi tiết ở "dashboard_pd_costbudget_1q.jsp" bên dưới), khiến DIRECT_COST_BDGT luôn = 0 -> bị lọc bởi
    // "WHERE DIRECT_COST_BDGT <> 0" -> Progress Actual % ra 0 dòng cho TOÀN BỘ dự án. Tiền tố đúng theo
    // CATB_STNDCLS: 'A%' = 1.Direct Cost (top-level, đã bao gồm cả Common Works/Expenses I bên trong).
    sql: `WITH DIRECT_COST_MONTHLY AS (
        SELECT FLDCODE,
               TO_NUMBER(SUBSTR(BASEYYMM, 1, 4)) AS YEAR,
               TO_NUMBER(SUBSTR(BASEYYMM, 5, 2)) AS MONTH,
               SUM(CASE WHEN STNDCLSCODE LIKE 'A%' THEN NVL(BDGTAMT, 0) ELSE 0 END) AS DIRECT_COST_BDGT,
               SUM(CASE WHEN STNDCLSCODE LIKE 'A%' THEN NVL(PFMAMT, 0) ELSE 0 END) AS DIRECT_COST_ACTUAL
        FROM CHTB_PFMCOSTRMRK
        GROUP BY FLDCODE, SUBSTR(BASEYYMM, 1, 4), SUBSTR(BASEYYMM, 5, 2)
    ),
    SNAPSHOT AS (
        SELECT FLDCODE, YEAR, MONTH,
               ROUND(DIRECT_COST_ACTUAL / NULLIF(DIRECT_COST_BDGT, 0) * 100, 4) AS ACTUAL_CUM_PCT
        FROM DIRECT_COST_MONTHLY
        WHERE DIRECT_COST_BDGT <> 0
    )
    SELECT
        S.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = S.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(S.FLDCODE) AS PROJECT_NAME,
        S.YEAR, S.MONTH,
        CAST(NULL AS NUMBER) AS PLAN_PCT,
        ROUND(S.ACTUAL_CUM_PCT - NVL(LAG(S.ACTUAL_CUM_PCT) OVER (PARTITION BY S.FLDCODE ORDER BY S.YEAR, S.MONTH), 0), 4) AS ACTUAL_PCT,
        CAST(NULL AS NUMBER) AS PLAN_CUM_PCT,
        S.ACTUAL_CUM_PCT
    FROM SNAPSHOT S
    ORDER BY PROJECT_NAME, S.YEAR, S.MONTH`,
  },

  "dashboard_pd_outsourcing_1q.jsp": {
    sql: `SELECT
        B.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = B.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(B.FLDCODE) AS PROJECT_NAME,
        T.SVCDVSCODE               AS TRADE_GROUP,
        T.ORDCONTTYPENAME          AS TRADE,
        FUN_GET_CTRT_CUST_INFO('2', B.FLDCODE, B.ORDCONTTYPECODE, B.CTRTCHGSEQ) AS VENDOR,
        T.SVCDVSCODE               AS CATEGORY,
        CASE WHEN LENGTH(B.CNSTDATE) = 8 THEN SUBSTR(B.CNSTDATE, 1, 4) || '-' || SUBSTR(B.CNSTDATE, 5, 2) || '-' || SUBSTR(B.CNSTDATE, 7, 2)
             ELSE B.CNSTDATE END AS CONTRACT_DATE,
        (SELECT NVL(SUM(TO_NUMBER(NVL(Z.CONTCHGYN, '0'))), 0)
         FROM CETB_PFMCTRTHIST Z
         WHERE Z.FLDCODE = B.FLDCODE
           AND Z.ORDCONTTYPECODE = B.ORDCONTTYPECODE
           AND Z.CTRTCHGSEQ <= B.CTRTCHGSEQ) AS CHANGE_NO,
        NVL(B.BDGTAMT, 0)          AS BUDGET,
        NVL(B.EXECAMT, 0)          AS EXECUTED_BUDGET,
        NVL(B.CTRTAMT, NVL(B.CTRTAMT_TAX, 0))      AS RESOLVED,
        NVL(S.PRGSAMT_TM, 0)       AS THIS_MONTH,
        NVL(S.PRGSAMT_AC, 0)       AS ACCUM,
        T.ORDCONTTYPECODE          AS SORT_ORDER
    FROM CDTB_ORDCONTTYPE T
    JOIN CETB_PFMCTRTHIST B
      ON B.FLDCODE = T.FLDCODE AND B.ORDCONTTYPECODE = T.ORDCONTTYPECODE
     AND B.LASTYN = '1'
    LEFT JOIN (
        SELECT FLDCODE, ORDCONTTYPECODE,
               SUM(DECODE(YYMM, TO_CHAR(SYSDATE, 'YYYYMM'), PRGSAMT, 0)) AS PRGSAMT_TM,
               SUM(PRGSAMT) AS PRGSAMT_AC
        FROM CETB_PFMSCHDHIST
        GROUP BY FLDCODE, ORDCONTTYPECODE
    ) S ON S.FLDCODE = B.FLDCODE AND S.ORDCONTTYPECODE = B.ORDCONTTYPECODE
    WHERE T.SVCDVSCODE IN ('1', '2')
      AND T.ORDCONTTYPECODE != '0000'
    ORDER BY B.FLDCODE, T.ORDCONTTYPECODE`,
  },

  "dashboard_pd_cashflow_1q.jsp": {
    sql: `WITH ACTUAL_DATA AS (
        SELECT X.SITE AS FLDCODE, TO_NUMBER(SUBSTR(X.TRANSACTIONDATE, 1, 4)) AS YEAR, TO_NUMBER(SUBSTR(X.TRANSACTIONDATE, 5, 2)) AS MONTH,
               DECODE(X.DEPOSITWITHDRAWAL, 'Income', 'INC', 'OUT') AS CATEGORY,
               ROUND(X.AMOUNT / NULLIF((SELECT MAX(R.CHGRATIO) KEEP (DENSE_RANK LAST ORDER BY R.YYMM) FROM CHTB_EXCHANGE_RATIO R WHERE R.EXCHANGE_TYPE = '.' AND R.BASEMONEY = 'VND' AND R.CHGMONEY = 'USD' AND R.YYMM <= SUBSTR(X.TRANSACTIONDATE, 1, 6)), 0), 2) AS AMOUNT
        FROM CFTB_CFTRANSACTION X
        JOIN CFTB_CASHFLOWTYPE T ON (T.CASHFLOWTYPECODE = X.CASHFLOWTYPE OR T.CASHFLOWTYPENAME = X.CASHFLOWTYPENAME)
        JOIN CATB_COMPANYSTRUCT_PROJECT P ON P.COMPCODE = X.COMPANY AND P.FLDCODE = X.SITE AND NVL(P.USEYN, 'Y') = 'Y'
        JOIN CATB_BUSILINE B ON B.BUSILINECODE = P.BUSILINECODE
        WHERE X.SITE IS NOT NULL AND UPPER(NVL(T.DISPLAYCASHFLOWREPORT, 'BUSILINE')) IN ('BUSILINE', 'BOTH')
          AND UPPER(NVL(B.CLASSIFICATION, '')) IN ('SITE', 'BUSILINE')
    ),
    MONTHLY AS (
        SELECT FLDCODE, YEAR, MONTH,
               SUM(CASE WHEN CATEGORY = 'INC' THEN AMOUNT ELSE 0 END) AS CASH_IN,
               SUM(CASE WHEN CATEGORY = 'OUT' THEN AMOUNT ELSE 0 END) AS CASH_OUT
        FROM ACTUAL_DATA
        WHERE MONTH BETWEEN 1 AND 12
        GROUP BY FLDCODE, YEAR, MONTH
    ),
    OPENBAL AS (
        SELECT FLDCODE, TOTALUSD, ROW_NUMBER() OVER (PARTITION BY FLDCODE ORDER BY OPENINGDATE) AS RN
        FROM CFTB_OPENINGBALANCE
    )
    SELECT
        M.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = M.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(M.FLDCODE) AS PROJECT_NAME,
        M.YEAR,
        M.MONTH,
        M.CASH_IN,
        M.CASH_OUT,
        NVL(OB.TOTALUSD, 0) + SUM(M.CASH_IN - M.CASH_OUT) OVER (PARTITION BY M.FLDCODE ORDER BY M.YEAR, M.MONTH) AS EQUIVALENT
    FROM MONTHLY M
    LEFT JOIN OPENBAL OB ON OB.FLDCODE = M.FLDCODE AND OB.RN = 1
    ORDER BY PROJECT_NAME, M.YEAR, M.MONTH`,
  },

  "dashboard_pd_cogs_monthly_1q.jsp": {
    sql: `WITH MONTHLY_COST_INVEST AS (
        SELECT
            I.FLDCODE,
            TO_NUMBER(SUBSTR(I.YYMM, 1, 4)) AS YEAR,
            TO_NUMBER(SUBSTR(I.YYMM, 5, 2)) AS MONTH,
            I.YYMM AS BASEYYMM,
            SUM(NVL(I.INVESTAMT, 0)) AS ACCT_COGS
        FROM CHTB_COST_INVEST I
        WHERE NVL(I.INVESTAMT, 0) > 0
        GROUP BY I.FLDCODE, I.YYMM
    ),
    MONTHLY_COST_DIRECT AS (
        SELECT
            C.FLDCODE,
            TO_NUMBER(SUBSTR(C.YYMM, 1, 4)) AS YEAR,
            TO_NUMBER(SUBSTR(C.YYMM, 5, 2)) AS MONTH,
            C.YYMM AS BASEYYMM,
            SUM(NVL(C.DEBITAMT, 0)) AS ACCT_COGS
        FROM CHTB_COST C
        WHERE NVL(C.DEBITAMT, 0) > 0
        GROUP BY C.FLDCODE, C.YYMM
    ),
    MONTHLY_ACCT_COGS AS (
        SELECT
            NVL(I.FLDCODE, D.FLDCODE) AS FLDCODE,
            NVL(I.YEAR, D.YEAR) AS YEAR,
            NVL(I.MONTH, D.MONTH) AS MONTH,
            NVL(I.BASEYYMM, D.BASEYYMM) AS BASEYYMM,
            CASE WHEN I.FLDCODE IS NOT NULL THEN I.ACCT_COGS ELSE D.ACCT_COGS END AS ACCT_COGS
        FROM MONTHLY_COST_DIRECT D
        LEFT JOIN MONTHLY_COST_INVEST I ON I.FLDCODE = D.FLDCODE AND I.BASEYYMM = D.BASEYYMM
    ),
    MONTHLY_WIP_COST AS (
        -- Tổng chi phí = Direct Cost ('A%', đã gồm Common/Expense I) + Expense II ('BWZJ%') + Contingency
        -- ('CWDD%') theo CATB_STNDCLS. Tiền tố 'ZAA/ZBA/ZCA/ZDA/ZZA' cũ SAI (không khớp bản ghi nào) nên
        -- WIP_COGS luôn ra 0 - xem comment chi tiết ở "dashboard_pd_costbudget_1q.jsp".
        SELECT
            P.FLDCODE,
            TO_NUMBER(SUBSTR(P.BASEYYMM, 1, 4)) AS YEAR,
            TO_NUMBER(SUBSTR(P.BASEYYMM, 5, 2)) AS MONTH,
            P.BASEYYMM,
            SUM(NVL(P.PFMAMT, 0)) AS WIP_COGS
        FROM CHTB_PFMCOSTRMRK P
        WHERE P.STNDCLSCODE LIKE 'A%'
           OR P.STNDCLSCODE LIKE 'BWZJ%'
           OR P.STNDCLSCODE LIKE 'CWDD%'
        GROUP BY P.FLDCODE, P.BASEYYMM
    ),
    ALL_PERIODS AS (
        SELECT FLDCODE, YEAR, MONTH, BASEYYMM FROM MONTHLY_ACCT_COGS
        UNION
        SELECT FLDCODE, YEAR, MONTH, BASEYYMM FROM MONTHLY_WIP_COST
    )
    SELECT
        AP.FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = AP.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(AP.FLDCODE) AS PROJECT_NAME,
        AP.YEAR,
        AP.MONTH,
        NVL(A.ACCT_COGS, 0) AS ACCT_COGS,
        NVL(W.WIP_COGS, 0) AS WIP_COGS,
        SUM(NVL(A.ACCT_COGS, 0)) OVER (PARTITION BY AP.FLDCODE, AP.YEAR ORDER BY AP.MONTH) AS CUMULATIVE_ACCT_COGS,
        SUM(NVL(W.WIP_COGS, 0)) OVER (PARTITION BY AP.FLDCODE, AP.YEAR ORDER BY AP.MONTH) AS CUMULATIVE_WIP_COGS
    FROM ALL_PERIODS AP
    LEFT JOIN MONTHLY_ACCT_COGS A ON A.FLDCODE = AP.FLDCODE AND A.BASEYYMM = AP.BASEYYMM
    LEFT JOIN MONTHLY_WIP_COST W ON W.FLDCODE = AP.FLDCODE AND W.BASEYYMM = AP.BASEYYMM
    ORDER BY PROJECT_NAME, YEAR, MONTH`,
  },

  "dashboard_pd_sales_1q.jsp": {
    sql: `SELECT
        NVL(P.FLDCODE, A.FLDCODE) AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = NVL(P.FLDCODE, A.FLDCODE)) AS SITE_CODE,
        FUN_GET_FLDNAME(NVL(P.FLDCODE, A.FLDCODE)) AS PROJECT_NAME,
        NVL(P.YEAR, A.YEAR) AS YEAR,
        NVL(P.MONTH, A.MONTH) AS MONTH,
        P.PLANAMT AS PLAN,
        A.PROGSALESAMT AS ACTUAL,
        ROUND(DECODE(P.PLANAMT, 0, 0, NVL(A.PROGSALESAMT, 0) / P.PLANAMT * 100), 2) AS MONTHLY_ACHIEVEMENT_PCT,
        SUM(NVL(A.PROGSALESAMT, 0)) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR) ORDER BY NVL(P.MONTH, A.MONTH)) AS ACTUAL_YTD,
        SUM(P.PLANAMT) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR)) AS ANNUAL_PLAN_TARGET,
        ROUND(DECODE(SUM(P.PLANAMT) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR)), 0, 0,
              SUM(NVL(A.PROGSALESAMT, 0)) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR) ORDER BY NVL(P.MONTH, A.MONTH))
              / SUM(P.PLANAMT) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR)) * 100), 2) AS ANNUAL_TARGET_ACHIEVEMENT_PCT
    FROM (
        SELECT FLDCODE, BASEYY AS YEAR, MONTH, SUM(PLANAMT) AS PLANAMT
        FROM (
            SELECT PP.FLDCODE, PP.BASEYY,
                   PP.PLAN1 AS M1, PP.PLAN2 AS M2, PP.PLAN3 AS M3, PP.PLAN4 AS M4,
                   PP.PLAN5 AS M5, PP.PLAN6 AS M6, PP.PLAN7 AS M7, PP.PLAN8 AS M8,
                   PP.PLAN9 AS M9, PP.PLAN10 AS M10, PP.PLAN11 AS M11, PP.PLAN12 AS M12
            FROM CJTB_BUSPLAN_DETL PP
        )
        UNPIVOT (PLANAMT FOR MONTH IN (M1 AS 1, M2 AS 2, M3 AS 3, M4 AS 4, M5 AS 5, M6 AS 6,
                                        M7 AS 7, M8 AS 8, M9 AS 9, M10 AS 10, M11 AS 11, M12 AS 12))
        GROUP BY FLDCODE, BASEYY, MONTH
    ) P
    FULL OUTER JOIN (
        SELECT FLDCODE, TO_NUMBER(SUBSTR(BASEYYMM, 1, 4)) AS YEAR,
               TO_NUMBER(SUBSTR(BASEYYMM, 5, 2)) AS MONTH, PROGSALESAMT
        FROM CJTB_SALESAMTRST
    ) A
      ON A.FLDCODE = P.FLDCODE AND A.YEAR = P.YEAR AND A.MONTH = P.MONTH
    WHERE FUN_GET_FLDNAME(NVL(P.FLDCODE, A.FLDCODE)) IS NOT NULL
    ORDER BY PROJECT_NAME, YEAR, MONTH`,
  },

  "dashboard_pd_costbudget_1q.jsp": {
    // STNDCLSCODE thực tế trong CHTB_PFMCOSTRMRK theo cây phân loại CATB_STNDCLS (KHÔNG dùng tiền tố
    // 'ZAA/ZBA/ZCA/ZDA/ZZA' như suy đoán ban đầu - không có bản ghi nào trong toàn bộ Oracle khớp các
    // tiền tố đó, khiến Budget Execution Status luôn ra 0 cho MỌI dự án). Tiền tố đúng theo CATB_STNDCLS:
    // A% = 1.Direct Cost (top), AWZH% = Common Works (con của Direct Cost), AWZI% = Expenses I (con của
    // Direct Cost), BWZJ% = Expenses II (con của Indirect Cost - 2.간접비), CWDD% = Contingency (con của
    // 3.예비비). Outsourcing = Direct Cost - Common - Expense1 (đúng như公式 cũ, chỉ sai tiền tố lọc).
    // Đồng thời bỏ nhóm theo YEAR: bảng đích pd_cost_budget không có cột year (1 dòng/hạng mục, không
    // phải 1 dòng/hạng mục/năm) - nhóm theo YEAR cũ tạo ra nhiều dòng trùng ITEM mỗi lần sync, và phía
    // Data Entry chỉ lấy dòng ĐẦU TIÊN tìm thấy (thường là năm cũ nhất) nên hiển thị sai lệch.
    sql: `WITH LATEST_SNAPSHOT AS (
        SELECT FLDCODE, MAX(BASEYYMM) AS MAX_BASEYYMM
        FROM CHTB_PFMCOSTRMRK
        GROUP BY FLDCODE
    ),
    COST_STATUS AS (
        SELECT
            A.FLDCODE,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'A%' THEN NVL(A.BDGTAMT, 0) ELSE 0 END) AS DIRECT_COST_BDGT,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'A%' THEN NVL(A.PFMAMT, 0) ELSE 0 END) AS DIRECT_COST_ACTUAL,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'AWZH%' THEN NVL(A.BDGTAMT, 0) ELSE 0 END) AS COMMON_BDGT,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'AWZH%' THEN NVL(A.PFMAMT, 0) ELSE 0 END) AS COMMON_ACTUAL,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'AWZI%' THEN NVL(A.BDGTAMT, 0) ELSE 0 END) AS EXPENSE1_BDGT,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'AWZI%' THEN NVL(A.PFMAMT, 0) ELSE 0 END) AS EXPENSE1_ACTUAL,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'BWZJ%' THEN NVL(A.BDGTAMT, 0) ELSE 0 END) AS EXPENSE2_BDGT,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'BWZJ%' THEN NVL(A.PFMAMT, 0) ELSE 0 END) AS EXPENSE2_ACTUAL,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'CWDD%' THEN NVL(A.BDGTAMT, 0) ELSE 0 END) AS CONTINGENCY_BDGT,
            SUM(CASE WHEN A.STNDCLSCODE LIKE 'CWDD%' THEN NVL(A.PFMAMT, 0) ELSE 0 END) AS CONTINGENCY_ACTUAL
        FROM CHTB_PFMCOSTRMRK A
        JOIN LATEST_SNAPSHOT S ON S.FLDCODE = A.FLDCODE AND S.MAX_BASEYYMM = A.BASEYYMM
        GROUP BY A.FLDCODE
    )
    SELECT
        C.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = C.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(C.FLDCODE) AS PROJECT_NAME,
        'Direct Cost' AS CATEGORY,
        'Outsourcing' AS ITEM,
        (C.DIRECT_COST_BDGT - C.COMMON_BDGT - C.EXPENSE1_BDGT) AS BUDGET,
        CAST(NULL AS NUMBER) AS PLAN,
        (C.DIRECT_COST_ACTUAL - C.COMMON_ACTUAL - C.EXPENSE1_ACTUAL) AS ACTUAL,
        ROUND(DECODE(C.DIRECT_COST_BDGT - C.COMMON_BDGT - C.EXPENSE1_BDGT, 0, 0,
              (C.DIRECT_COST_ACTUAL - C.COMMON_ACTUAL - C.EXPENSE1_ACTUAL) / (C.DIRECT_COST_BDGT - C.COMMON_BDGT - C.EXPENSE1_BDGT) * 100), 2) AS EXECUTION_RATE,
        1 AS SORT_ORDER
    FROM COST_STATUS C
    UNION ALL
    SELECT
        C.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = C.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(C.FLDCODE) AS PROJECT_NAME,
        'Direct Cost' AS CATEGORY,
        'Common' AS ITEM,
        C.COMMON_BDGT AS BUDGET,
        CAST(NULL AS NUMBER) AS PLAN,
        C.COMMON_ACTUAL AS ACTUAL,
        ROUND(DECODE(C.COMMON_BDGT, 0, 0, C.COMMON_ACTUAL / C.COMMON_BDGT * 100), 2) AS EXECUTION_RATE,
        2 AS SORT_ORDER
    FROM COST_STATUS C
    UNION ALL
    SELECT
        C.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = C.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(C.FLDCODE) AS PROJECT_NAME,
        'Direct Cost' AS CATEGORY,
        'Expense 1' AS ITEM,
        C.EXPENSE1_BDGT AS BUDGET,
        CAST(NULL AS NUMBER) AS PLAN,
        C.EXPENSE1_ACTUAL AS ACTUAL,
        ROUND(DECODE(C.EXPENSE1_BDGT, 0, 0, C.EXPENSE1_ACTUAL / C.EXPENSE1_BDGT * 100), 2) AS EXECUTION_RATE,
        3 AS SORT_ORDER
    FROM COST_STATUS C
    UNION ALL
    SELECT
        C.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = C.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(C.FLDCODE) AS PROJECT_NAME,
        CAST(NULL AS VARCHAR2(20)) AS CATEGORY,
        'Direct cost' AS ITEM,
        C.DIRECT_COST_BDGT AS BUDGET,
        CAST(NULL AS NUMBER) AS PLAN,
        C.DIRECT_COST_ACTUAL AS ACTUAL,
        ROUND(DECODE(C.DIRECT_COST_BDGT, 0, 0, C.DIRECT_COST_ACTUAL / C.DIRECT_COST_BDGT * 100), 2) AS EXECUTION_RATE,
        4 AS SORT_ORDER
    FROM COST_STATUS C
    UNION ALL
    SELECT
        C.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = C.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(C.FLDCODE) AS PROJECT_NAME,
        'Indirect Cost' AS CATEGORY,
        'Expense 2' AS ITEM,
        C.EXPENSE2_BDGT AS BUDGET,
        CAST(NULL AS NUMBER) AS PLAN,
        C.EXPENSE2_ACTUAL AS ACTUAL,
        ROUND(DECODE(C.EXPENSE2_BDGT, 0, 0, C.EXPENSE2_ACTUAL / C.EXPENSE2_BDGT * 100), 2) AS EXECUTION_RATE,
        5 AS SORT_ORDER
    FROM COST_STATUS C
    UNION ALL
    SELECT
        C.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = C.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(C.FLDCODE) AS PROJECT_NAME,
        'Indirect Cost' AS CATEGORY,
        'Contingency' AS ITEM,
        C.CONTINGENCY_BDGT AS BUDGET,
        CAST(NULL AS NUMBER) AS PLAN,
        C.CONTINGENCY_ACTUAL AS ACTUAL,
        ROUND(DECODE(C.CONTINGENCY_BDGT, 0, 0, C.CONTINGENCY_ACTUAL / C.CONTINGENCY_BDGT * 100), 2) AS EXECUTION_RATE,
        6 AS SORT_ORDER
    FROM COST_STATUS C
    ORDER BY PROJECT_NAME, SORT_ORDER`,
  },

  "dashboard_pd_costestimation_1q.jsp": {
    // Cost Rate — CHỈ mục "Execution Budget" (실행예산원가율). Bidding và Estimated Completion chưa có
    // nguồn PIMS đáng tin cậy đã xác minh (xem MaTran_NguonDuLieu_Dashboard_PIMS_DECV_v4.xlsx #12/#14) —
    // vẫn giữ nhập tay. Nguồn: CDTB_PFMSUM_VINA join CDTB_PFMCHGSEQ lọc BDGTTYPECODE='1' (Execution
    // Budget - xác minh qua COMPRSN/TITLE1/TITLE2 thực tế, khác '0'=Initial/Bidding và '2'=Change/test)
    // và APPRSTSCODE='40' (đã duyệt), lấy PFMCHGSEQ mới nhất còn thoả điều kiện.
    sql: `WITH EXEC_BUDGET_SEQ AS (
        SELECT FLDCODE, MAX(PFMCHGSEQ) AS PFMCHGSEQ
        FROM CDTB_PFMCHGSEQ
        WHERE BDGTTYPECODE = '1' AND APPRSTSCODE = '40'
        GROUP BY FLDCODE
    )
    SELECT
        P.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = P.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(P.FLDCODE) AS PROJECT_NAME,
        MAX(CASE WHEN P.STNDCODE = 'ZYA' THEN P.BDGTAMT END) AS COST_AMOUNT,
        MAX(CASE WHEN P.STNDCODE = 'ZZL' THEN P.BDGTAMT END) AS CONTRACT_AMOUNT
    FROM CDTB_PFMSUM_VINA P
    JOIN EXEC_BUDGET_SEQ S ON S.FLDCODE = P.FLDCODE AND S.PFMCHGSEQ = P.PFMCHGSEQ
    WHERE P.CURCODE = 'USD' AND P.STNDCODE IN ('ZYA', 'ZZL')
    GROUP BY P.FLDCODE
    ORDER BY PROJECT_NAME`,
  },

  "dashboard_pd_milestones_1q.jsp": {
    sql: `SELECT
        H.FLDCODE                                         AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = H.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(H.FLDCODE)                        AS PROJECT_NAME,
        FUN_GET_CA_REFFPF('37', H.HISTTYPEDVSCODE, 'KR')  AS LABEL,
        CAST(NULL AS VARCHAR2(7))                         AS PLAN_START,
        CAST(NULL AS VARCHAR2(7))                         AS PLAN_END,
        CASE WHEN REGEXP_LIKE(H.HISTDATE, '^[0-9]{8}$') THEN SUBSTR(H.HISTDATE, 1, 4) || '-' || SUBSTR(H.HISTDATE, 5, 2) END AS ACTUAL_START,
        CASE WHEN REGEXP_LIKE(H.HISTDATE, '^[0-9]{8}$') THEN SUBSTR(H.HISTDATE, 1, 4) || '-' || SUBSTR(H.HISTDATE, 5, 2) END AS ACTUAL_END,
        ROW_NUMBER() OVER (PARTITION BY H.FLDCODE ORDER BY H.HISTDATE)          AS SORT_ORDER
    FROM CBTB_CONSTHISTORY H
    ORDER BY PROJECT_NAME, H.HISTDATE`,
  },

  "dashboard_common_siterate_1q.jsp": {
    sql: `SELECT
        A.FLDCODE,
        A.CTRTCURCODE,
        A.LCLCURCODE,
        A.BASECURCODE,
        A.RATEUSD AS RATE_USD,
        A.RATEKRW AS RATE_KRW
    FROM CBTB_CTRTSUMM A
    WHERE UPPER(A.FLDCODE) = UPPER(:site_code)`,
    binds: (params) => ({ site_code: params.site_code ?? "" }),
  },

  "dashboard_common_exchangerate_1q.jsp": {
    sql: `SELECT
        R.EXCHANGE_TYPE,
        R.BASEMONEY,
        R.CHGMONEY,
        R.YYMM,
        R.CHGRATIO AS RATE
    FROM CHTB_EXCHANGE_RATIO R
    WHERE R.EXCHANGE_TYPE = '.'
        AND R.BASEMONEY IN ('VND', 'USD', 'JYP', 'KRW')
        AND R.CHGMONEY IN ('VND', 'USD', 'JYP', 'KRW')
        AND R.YYMM = (SELECT MAX(YYMM) FROM CHTB_EXCHANGE_RATIO WHERE EXCHANGE_TYPE = '.' AND YYMM <= :as_of)
    ORDER BY R.CHGMONEY`,
    binds: (params) => ({ as_of: params.as_of || currentYYYYMM() }),
  },
};
