/**
 * SQL lấy nguyên văn từ site/jsp/Common/dashboard/dashboard_*.jsp trong repo `pimsvina`
 * (d:\code\pimsvina) — dùng để query thẳng Oracle (PIMSVINA) thay vì gọi REST + JWT qua Tomcat.
 * Mỗi lần đồng bộ SQL phía JSP, phải copy lại đúng nguyên văn vào đây để tránh lệch dữ liệu.
 */

function currentYYYYMM(): string {
  const d = new Date();
  return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export interface OracleEndpointQuery {
  sql: string;
  /** node-oracledb dùng named bind (:name), khác với `?` JDBC gốc trong JSP. */
  binds?: (params: Record<string, string>) => Record<string, unknown>;
}

export const ORACLE_DASHBOARD_QUERIES: Record<string, OracleEndpointQuery> = {
  "dashboard_pd_overview_1q.jsp": {
    // Chỉ lấy đúng 6 cột dùng trên UI (bỏ Client/Scale/Base Month/Scope/Revenue*/Cash*), không NVL
    // dự phòng giữa nhiều nguồn — Contract Amount lấy thẳng CBTB_CTRTSUMM, Start/End Date lấy thẳng
    // dòng CBTB_CONSTPERIOD mới nhất (CHGSEQ lớn nhất) theo từng dự án.
    sql: `SELECT
        A.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = A.FLDCODE) AS SITE_CODE,
        A.FLDNAME AS PROJECT_NAME,
        CT.TOTALCTRTWONAMT AS CONTRACT_AMOUNT,
        SUBSTR(NVL(CP.CTRTSTDATE, ''), 1, 4) || '-' || SUBSTR(NVL(CP.CTRTSTDATE, ''), 5, 2) || '-' || SUBSTR(NVL(CP.CTRTSTDATE, ''), 7, 2) AS START_DATE,
        SUBSTR(NVL(CP.CTRTEDDATE, ''), 1, 4) || '-' || SUBSTR(NVL(CP.CTRTEDDATE, ''), 5, 2) || '-' || SUBSTR(NVL(CP.CTRTEDDATE, ''), 7, 2) AS END_DATE
    FROM CBTB_FLDSUMM A
    LEFT JOIN CBTB_CTRTSUMM CT ON CT.FLDCODE = A.FLDCODE
    LEFT JOIN (
        SELECT FLDCODE, CTRTSTDATE, CTRTEDDATE
        FROM (SELECT P.*, ROW_NUMBER() OVER (PARTITION BY P.FLDCODE ORDER BY P.CHGSEQ DESC) AS RN FROM CBTB_CONSTPERIOD P)
        WHERE RN = 1
    ) CP ON CP.FLDCODE = A.FLDCODE
    ORDER BY SITE_CODE`,
  },

  "dashboard_pd_progress_1q.jsp": {
    // Công thức mới (thay thế công thức SRD §2-2 cũ): Monthly Actual (%) = SUM_COSTAMT / (SUM_BDGTAMT -
    // DIFF_BUDGET_VS_IMPLEMENTATION). SUM_BDGTAMT/SUM_COSTAMT lấy từ CHTB_PFMCOSTRMRK (RMRKLVL=1, đã verify
    // khớp màn hình "Cost Input Status by Execution Details"/"Cost Performance"), DIFF_BUDGET_VS_IMPLEMENTATION
    // = |SUM(Execution Budget) - SUM(Implementation Amount)| lấy từ CETB_PFMCTRTHIST (đã verify khớp màn hình
    // "Request Execution Resolution(Site)", chỉ lấy dòng CTRTCHGSEQ mới nhất mỗi ORDCONTTYPECODE - cờ TREE=0,
    // loại các ORDCONTTYPECODE có bản ghi CTRTTYPE='1' (현장)). Chỉ trả về đúng các cột: FLDCODE, SITE_CODE,
    // PROJECT_NAME, YEAR, MONTH, ACTUAL_PCT — KHÔNG còn PLAN_PCT/PLAN_CUM_PCT/ACTUAL_CUM_PCT (sync chỉ cập
    // nhật đúng actualPct, không đụng tới các trường luỹ kế/kế hoạch khác).
    sql: `WITH CTE_RMRK AS (
        SELECT A.FLDCODE, A.BASEYYMM, SUM(A.BDGTAMT) AS SUM_BDGTAMT
        FROM CHTB_PFMCOSTRMRK A
        WHERE A.RMRKLVL = 1
        GROUP BY A.FLDCODE, A.BASEYYMM
    ),
    CTE_COST AS (
        SELECT A.FLDCODE, A.BASEYYMM, SUM(A.COSTAMT) AS SUM_COSTAMT
        FROM CHTB_PFMCOSTRMRK A
        WHERE A.RMRKLVL = 1
        GROUP BY A.FLDCODE, A.BASEYYMM
    ),
    CTE_DIFF AS (
        SELECT FLDCODE, ABS(SUM(EXECUTION_BUDGET) - SUM(IMPLEMENTATION_AMT)) AS DIFF_BUDGET_VS_IMPLEMENTATION
        FROM (
            SELECT
                CASE WHEN COUNT(*) OVER (PARTITION BY A.FLDCODE, NVL(A.ORDCONTTYPECODE, 'X')) = 1 OR
                          MAX(NVL(B.CTRTCHGSEQ, 0)) OVER (PARTITION BY A.FLDCODE, NVL(A.ORDCONTTYPECODE, 'X')) = NVL(B.CTRTCHGSEQ, 0)
                     THEN 0 ELSE 1 END AS TREE,
                A.FLDCODE,
                B.BDGTAMT AS EXECUTION_BUDGET,
                B.CTRTAMT AS IMPLEMENTATION_AMT
            FROM CDTB_ORDCONTTYPE A, CETB_PFMCTRTHIST B
            WHERE A.FLDCODE = B.FLDCODE(+)
              AND A.ORDCONTTYPECODE = B.ORDCONTTYPECODE(+)
              AND NOT EXISTS (
                      SELECT 1 FROM CETB_PFMCTRTHIST
                      WHERE FLDCODE = A.FLDCODE AND ORDCONTTYPECODE = A.ORDCONTTYPECODE AND CTRTTYPE = '1'
                  )
        )
        WHERE TREE = 0
        GROUP BY FLDCODE
    ),
    CTE_MONTHLY AS (
        SELECT R.FLDCODE, R.BASEYYMM,
               C.SUM_COSTAMT / NULLIF(R.SUM_BDGTAMT - D.DIFF_BUDGET_VS_IMPLEMENTATION, 0) AS ACTUAL_PCT
        FROM CTE_RMRK R
        JOIN CTE_COST C ON C.FLDCODE = R.FLDCODE AND C.BASEYYMM = R.BASEYYMM
        JOIN CTE_DIFF D ON D.FLDCODE = R.FLDCODE
    )
    SELECT
        M.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = M.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(M.FLDCODE) AS PROJECT_NAME,
        TO_NUMBER(SUBSTR(M.BASEYYMM, 1, 4)) AS YEAR,
        TO_NUMBER(SUBSTR(M.BASEYYMM, 5, 2)) AS MONTH,
        ROUND(M.ACTUAL_PCT * 100, 4) AS ACTUAL_PCT
    FROM CTE_MONTHLY M
    ORDER BY PROJECT_NAME, M.BASEYYMM`,
  },

  "dashboard_pd_outsourcing_1q.jsp": {
    sql: `SELECT
        B.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = B.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(B.FLDCODE) AS PROJECT_NAME,
        T.SVCDVSCODE               AS TRADE_GROUP,
        T.ORDCONTTYPENAME          AS TRADE,
        FUN_GET_CTRT_CUST_INFO('2', B.FLDCODE, B.ORDCONTTYPECODE, B.CTRTCHGSEQ) AS VENDOR,
        T.SVCDVSCODE               AS CATEGORY,
        CASE WHEN LENGTH(B.CNSTDATE) = 8 THEN SUBSTR(B.CNSTDATE, 1, 4) || '-' || SUBSTR(B.CNSTDATE, 5, 2) || '-' || SUBSTR(B.CNSTDATE, 7, 2)
             ELSE B.CNSTDATE END AS CONTRACT_DATE,
        (SELECT NVL(SUM(TO_NUMBER(NVL(Z.CONTCHGYN, '0'))), 0)
         FROM CETB_PFMCTRTHIST Z
         WHERE Z.FLDCODE = B.FLDCODE
           AND Z.ORDCONTTYPECODE = B.ORDCONTTYPECODE
           AND Z.CTRTCHGSEQ <= B.CTRTCHGSEQ) AS CHANGE_NO,
        NVL(B.BDGTAMT, 0)          AS BUDGET,
        NVL(B.EXECAMT, 0)          AS EXECUTED_BUDGET,
        NVL(B.CTRTAMT, NVL(B.CTRTAMT_TAX, 0))      AS RESOLVED,
        NVL(S.PRGSAMT_TM, 0)       AS THIS_MONTH,
        NVL(S.PRGSAMT_AC, 0)       AS ACCUM,
        T.ORDCONTTYPECODE          AS SORT_ORDER
    FROM CDTB_ORDCONTTYPE T
    JOIN CETB_PFMCTRTHIST B
      ON B.FLDCODE = T.FLDCODE AND B.ORDCONTTYPECODE = T.ORDCONTTYPECODE
     AND B.LASTYN = '1'
    LEFT JOIN (
        SELECT FLDCODE, ORDCONTTYPECODE,
               SUM(DECODE(YYMM, TO_CHAR(SYSDATE, 'YYYYMM'), PRGSAMT, 0)) AS PRGSAMT_TM,
               SUM(PRGSAMT) AS PRGSAMT_AC
        FROM CETB_PFMSCHDHIST
        GROUP BY FLDCODE, ORDCONTTYPECODE
    ) S ON S.FLDCODE = B.FLDCODE AND S.ORDCONTTYPECODE = B.ORDCONTTYPECODE
    WHERE T.SVCDVSCODE IN ('1', '2')
      AND T.ORDCONTTYPECODE != '0000'
    ORDER BY B.FLDCODE, T.ORDCONTTYPECODE`,
  },

  "dashboard_pd_trade_cost_monthly_1q.jsp": {
    sql: `SELECT
        S.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = S.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(S.FLDCODE) AS PROJECT_NAME,
        T.SVCDVSCODE AS TRADE_GROUP,
        T.ORDCONTTYPECODE AS TRADE_CODE,
        T.ORDCONTTYPENAME AS TRADE,
        TO_NUMBER(SUBSTR(S.YYMM, 1, 4)) AS YEAR,
        TO_NUMBER(SUBSTR(S.YYMM, 5, 2)) AS MONTH,
        CAST('VND' AS VARCHAR2(3)) AS SOURCE_CURRENCY,
        SUM(NVL(S.PRGSAMT, 0)) AS ACTUAL_VND,
        ROUND(
          SUM(NVL(S.PRGSAMT, 0))
          / NULLIF((
              SELECT MAX(R.CHGRATIO) KEEP (DENSE_RANK LAST ORDER BY R.YYMM)
              FROM CHTB_EXCHANGE_RATIO R
              WHERE R.EXCHANGE_TYPE = '.'
                AND R.BASEMONEY = 'VND'
                AND R.CHGMONEY = 'USD'
                AND R.YYMM <= S.YYMM
            ), 0)
          / 1000,
          8
        ) AS ACTUAL_KUSD
    FROM CETB_PFMSCHDHIST S
    JOIN CDTB_ORDCONTTYPE T
      ON T.FLDCODE = S.FLDCODE
     AND T.ORDCONTTYPECODE = S.ORDCONTTYPECODE
    JOIN CETB_PFMCTRTHIST B
      ON B.FLDCODE = S.FLDCODE
     AND B.ORDCONTTYPECODE = S.ORDCONTTYPECODE
     AND B.LASTYN = '1'
    WHERE T.SVCDVSCODE IN ('1', '2')
      AND T.ORDCONTTYPECODE != '0000'
      AND LENGTH(S.YYMM) = 6
    GROUP BY
        S.FLDCODE,
        T.SVCDVSCODE,
        T.ORDCONTTYPECODE,
        T.ORDCONTTYPENAME,
        S.YYMM
    ORDER BY S.FLDCODE, S.YYMM, T.ORDCONTTYPECODE`,
  },

  "dashboard_pd_trade_cost_scopes_1q.jsp": {
    sql: `SELECT DISTINCT
        P.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = P.FLDCODE) AS SITE_CODE,
        TO_NUMBER(SUBSTR(P.BASEYYMM, 1, 4)) AS YEAR
    FROM CHTB_PFMCOSTRMRK P
    WHERE LENGTH(P.BASEYYMM) = 6
    ORDER BY P.FLDCODE, YEAR`,
  },

  "dashboard_pd_cashflow_1q.jsp": {
    sql: `WITH ACTUAL_DATA AS (
        SELECT X.SITE AS FLDCODE, TO_NUMBER(SUBSTR(X.TRANSACTIONDATE, 1, 4)) AS YEAR, TO_NUMBER(SUBSTR(X.TRANSACTIONDATE, 5, 2)) AS MONTH,
               DECODE(X.DEPOSITWITHDRAWAL, 'Income', 'INC', 'OUT') AS CATEGORY,
               ROUND(X.AMOUNT / NULLIF((SELECT MAX(R.CHGRATIO) KEEP (DENSE_RANK LAST ORDER BY R.YYMM) FROM CHTB_EXCHANGE_RATIO R WHERE R.EXCHANGE_TYPE = '.' AND R.BASEMONEY = 'VND' AND R.CHGMONEY = 'USD' AND R.YYMM <= SUBSTR(X.TRANSACTIONDATE, 1, 6)), 0), 2) AS AMOUNT
        FROM CFTB_CFTRANSACTION X
        JOIN CFTB_CASHFLOWTYPE T ON (T.CASHFLOWTYPECODE = X.CASHFLOWTYPE OR T.CASHFLOWTYPENAME = X.CASHFLOWTYPENAME)
        JOIN CATB_COMPANYSTRUCT_PROJECT P ON P.COMPCODE = X.COMPANY AND P.FLDCODE = X.SITE AND NVL(P.USEYN, 'Y') = 'Y'
        JOIN CATB_BUSILINE B ON B.BUSILINECODE = P.BUSILINECODE
        WHERE X.SITE IS NOT NULL AND UPPER(NVL(T.DISPLAYCASHFLOWREPORT, 'BUSILINE')) IN ('BUSILINE', 'BOTH')
          AND UPPER(NVL(B.CLASSIFICATION, '')) IN ('SITE', 'BUSILINE')
    ),
    MONTHLY AS (
        SELECT FLDCODE, YEAR, MONTH,
               SUM(CASE WHEN CATEGORY = 'INC' THEN AMOUNT ELSE 0 END) AS CASH_IN,
               SUM(CASE WHEN CATEGORY = 'OUT' THEN AMOUNT ELSE 0 END) AS CASH_OUT
        FROM ACTUAL_DATA
        WHERE MONTH BETWEEN 1 AND 12
        GROUP BY FLDCODE, YEAR, MONTH
    ),
    OPENBAL AS (
        SELECT FLDCODE, TOTALUSD, ROW_NUMBER() OVER (PARTITION BY FLDCODE ORDER BY OPENINGDATE) AS RN
        FROM CFTB_OPENINGBALANCE
    )
    SELECT
        M.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = M.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(M.FLDCODE) AS PROJECT_NAME,
        M.YEAR,
        M.MONTH,
        M.CASH_IN,
        M.CASH_OUT,
        NVL(OB.TOTALUSD, 0) + SUM(M.CASH_IN - M.CASH_OUT) OVER (PARTITION BY M.FLDCODE ORDER BY M.YEAR, M.MONTH) AS EQUIVALENT
    FROM MONTHLY M
    LEFT JOIN OPENBAL OB ON OB.FLDCODE = M.FLDCODE AND OB.RN = 1
    ORDER BY PROJECT_NAME, M.YEAR, M.MONTH`,
  },

  "dashboard_pd_cogs_monthly_1q.jsp": {
    sql: `WITH MONTHLY_COST_INVEST AS (
        SELECT
            I.FLDCODE,
            TO_NUMBER(SUBSTR(I.YYMM, 1, 4)) AS YEAR,
            TO_NUMBER(SUBSTR(I.YYMM, 5, 2)) AS MONTH,
            I.YYMM AS BASEYYMM,
            SUM(NVL(I.INVESTAMT, 0)) AS ACCT_COGS
        FROM CHTB_COST_INVEST I
        WHERE NVL(I.INVESTAMT, 0) > 0
        GROUP BY I.FLDCODE, I.YYMM
    ),
    MONTHLY_COST_DIRECT AS (
        SELECT
            C.FLDCODE,
            TO_NUMBER(SUBSTR(C.YYMM, 1, 4)) AS YEAR,
            TO_NUMBER(SUBSTR(C.YYMM, 5, 2)) AS MONTH,
            C.YYMM AS BASEYYMM,
            SUM(NVL(C.DEBITAMT, 0)) AS ACCT_COGS
        FROM CHTB_COST C
        WHERE NVL(C.DEBITAMT, 0) > 0
        GROUP BY C.FLDCODE, C.YYMM
    ),
    MONTHLY_ACCT_COGS AS (
        SELECT
            NVL(I.FLDCODE, D.FLDCODE) AS FLDCODE,
            NVL(I.YEAR, D.YEAR) AS YEAR,
            NVL(I.MONTH, D.MONTH) AS MONTH,
            NVL(I.BASEYYMM, D.BASEYYMM) AS BASEYYMM,
            CASE WHEN I.FLDCODE IS NOT NULL THEN I.ACCT_COGS ELSE D.ACCT_COGS END AS ACCT_COGS
        FROM MONTHLY_COST_DIRECT D
        LEFT JOIN MONTHLY_COST_INVEST I ON I.FLDCODE = D.FLDCODE AND I.BASEYYMM = D.BASEYYMM
    ),
    MONTHLY_WIP_COST AS (
        -- Tổng chi phí = Direct Cost ('A%', đã gồm Common/Expense I) + Expense II ('BWZJ%') + Contingency
        -- ('CWDD%') theo CATB_STNDCLS. Tiền tố 'ZAA/ZBA/ZCA/ZDA/ZZA' cũ SAI (không khớp bản ghi nào) nên
        -- WIP_COGS luôn ra 0 - xem comment chi tiết ở "dashboard_pd_costbudget_1q.jsp".
        SELECT
            P.FLDCODE,
            TO_NUMBER(SUBSTR(P.BASEYYMM, 1, 4)) AS YEAR,
            TO_NUMBER(SUBSTR(P.BASEYYMM, 5, 2)) AS MONTH,
            P.BASEYYMM,
            SUM(NVL(P.PFMAMT, 0)) AS WIP_COGS
        FROM CHTB_PFMCOSTRMRK P
        WHERE P.STNDCLSCODE LIKE 'A%'
           OR P.STNDCLSCODE LIKE 'BWZJ%'
           OR P.STNDCLSCODE LIKE 'CWDD%'
        GROUP BY P.FLDCODE, P.BASEYYMM
    ),
    ALL_PERIODS AS (
        SELECT FLDCODE, YEAR, MONTH, BASEYYMM FROM MONTHLY_ACCT_COGS
        UNION
        SELECT FLDCODE, YEAR, MONTH, BASEYYMM FROM MONTHLY_WIP_COST
    )
    SELECT
        AP.FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = AP.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(AP.FLDCODE) AS PROJECT_NAME,
        AP.YEAR,
        AP.MONTH,
        NVL(A.ACCT_COGS, 0) AS ACCT_COGS,
        NVL(W.WIP_COGS, 0) AS WIP_COGS,
        SUM(NVL(A.ACCT_COGS, 0)) OVER (PARTITION BY AP.FLDCODE, AP.YEAR ORDER BY AP.MONTH) AS CUMULATIVE_ACCT_COGS,
        SUM(NVL(W.WIP_COGS, 0)) OVER (PARTITION BY AP.FLDCODE, AP.YEAR ORDER BY AP.MONTH) AS CUMULATIVE_WIP_COGS
    FROM ALL_PERIODS AP
    LEFT JOIN MONTHLY_ACCT_COGS A ON A.FLDCODE = AP.FLDCODE AND A.BASEYYMM = AP.BASEYYMM
    LEFT JOIN MONTHLY_WIP_COST W ON W.FLDCODE = AP.FLDCODE AND W.BASEYYMM = AP.BASEYYMM
    ORDER BY PROJECT_NAME, YEAR, MONTH`,
  },

  "dashboard_pd_sales_1q.jsp": {
    sql: `SELECT
        NVL(P.FLDCODE, A.FLDCODE) AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = NVL(P.FLDCODE, A.FLDCODE)) AS SITE_CODE,
        FUN_GET_FLDNAME(NVL(P.FLDCODE, A.FLDCODE)) AS PROJECT_NAME,
        NVL(P.YEAR, A.YEAR) AS YEAR,
        NVL(P.MONTH, A.MONTH) AS MONTH,
        P.PLANAMT AS PLAN,
        A.PROGSALESAMT AS ACTUAL,
        ROUND(DECODE(P.PLANAMT, 0, 0, NVL(A.PROGSALESAMT, 0) / P.PLANAMT * 100), 2) AS MONTHLY_ACHIEVEMENT_PCT,
        SUM(NVL(A.PROGSALESAMT, 0)) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR) ORDER BY NVL(P.MONTH, A.MONTH)) AS ACTUAL_YTD,
        SUM(P.PLANAMT) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR)) AS ANNUAL_PLAN_TARGET,
        ROUND(DECODE(SUM(P.PLANAMT) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR)), 0, 0,
              SUM(NVL(A.PROGSALESAMT, 0)) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR) ORDER BY NVL(P.MONTH, A.MONTH))
              / SUM(P.PLANAMT) OVER (PARTITION BY NVL(P.FLDCODE, A.FLDCODE), NVL(P.YEAR, A.YEAR)) * 100), 2) AS ANNUAL_TARGET_ACHIEVEMENT_PCT
    FROM (
        SELECT FLDCODE, BASEYY AS YEAR, MONTH, SUM(PLANAMT) AS PLANAMT
        FROM (
            SELECT PP.FLDCODE, PP.BASEYY,
                   PP.PLAN1 AS M1, PP.PLAN2 AS M2, PP.PLAN3 AS M3, PP.PLAN4 AS M4,
                   PP.PLAN5 AS M5, PP.PLAN6 AS M6, PP.PLAN7 AS M7, PP.PLAN8 AS M8,
                   PP.PLAN9 AS M9, PP.PLAN10 AS M10, PP.PLAN11 AS M11, PP.PLAN12 AS M12
            FROM CJTB_BUSPLAN_DETL PP
        )
        UNPIVOT (PLANAMT FOR MONTH IN (M1 AS 1, M2 AS 2, M3 AS 3, M4 AS 4, M5 AS 5, M6 AS 6,
                                        M7 AS 7, M8 AS 8, M9 AS 9, M10 AS 10, M11 AS 11, M12 AS 12))
        GROUP BY FLDCODE, BASEYY, MONTH
    ) P
    FULL OUTER JOIN (
        SELECT FLDCODE, TO_NUMBER(SUBSTR(BASEYYMM, 1, 4)) AS YEAR,
               TO_NUMBER(SUBSTR(BASEYYMM, 5, 2)) AS MONTH, PROGSALESAMT
        FROM CJTB_SALESAMTRST
    ) A
      ON A.FLDCODE = P.FLDCODE AND A.YEAR = P.YEAR AND A.MONTH = P.MONTH
    WHERE FUN_GET_FLDNAME(NVL(P.FLDCODE, A.FLDCODE)) IS NOT NULL
    ORDER BY PROJECT_NAME, YEAR, MONTH`,
  },

  "dashboard_pd_costbudget_1q.jsp": {
    // Công thức mới: BUDGET lấy từ CHTB_PFMCOSTRMRK.BDGTAMT (RMRKLVL=2, đã verify khớp màn hình "Cost Input
    // Status by Execution Details") của snapshot THÁNG GẦN NHẤT mỗi dự án; ACTUAL = luỹ kế COSTAMT từ tháng
    // đầu tiên có dữ liệu đến đúng tháng đó (đã verify khớp cột "Cumulative Amount" cùng màn hình). Mỗi dòng
    // RMRKLVL=2 (DETLNAME) được map vào 1 trong 5 item chuẩn của dashboard: Common Work→Common, Expense I→
    // Expense 1, Expense II→Expense 2, Contingency→Contingency, còn lại (Architectural/Mechanical/Electrical/
    // External & Landscape Works, và bất kỳ hạng mục thầu phụ nào khác chưa liệt kê) → Outsourcing (mặc định).
    sql: `WITH CTE_RMRK AS (
        SELECT A.FLDCODE, A.BASEYYMM, A.RMRKMGTNO, A.DETLNAME, A.BDGTAMT
        FROM CHTB_PFMCOSTRMRK A
        WHERE A.RMRKLVL = 2
    ),
    CTE_COST AS (
        SELECT FLDCODE, BASEYYMM, RMRKMGTNO, SUM(NVL(COSTAMT, 0)) AS COSTAMT_MONTH
        FROM CHTB_PFMCOSTRMRK
        GROUP BY FLDCODE, BASEYYMM, RMRKMGTNO
    ),
    CTE_ITEM AS (
        SELECT
            A.FLDCODE,
            A.BASEYYMM,
            CASE
                WHEN A.DETLNAME = 'Common Work'  THEN 'Common'
                WHEN A.DETLNAME = 'Expense I'    THEN 'Expense 1'
                WHEN A.DETLNAME = 'Expense II'   THEN 'Expense 2'
                WHEN A.DETLNAME = 'Contingency'  THEN 'Contingency'
                ELSE 'Outsourcing'
            END AS ITEM,
            CASE
                WHEN A.DETLNAME = 'Expense II'   THEN 'Indirect Cost'
                WHEN A.DETLNAME = 'Contingency'  THEN 'Contingency'
                ELSE 'Direct Cost'
            END AS CATEGORY,
            A.BDGTAMT,
            C.COSTAMT_MONTH
        FROM CTE_RMRK A
        JOIN CTE_COST C ON C.FLDCODE = A.FLDCODE AND C.BASEYYMM = A.BASEYYMM AND C.RMRKMGTNO = A.RMRKMGTNO
    ),
    CTE_GROUPED AS (
        SELECT FLDCODE, BASEYYMM, ITEM, CATEGORY,
               SUM(BDGTAMT) AS BUDGET,
               SUM(COSTAMT_MONTH) AS COSTAMT_MONTH_SUM
        FROM CTE_ITEM
        GROUP BY FLDCODE, BASEYYMM, ITEM, CATEGORY
    ),
    CTE_LATEST AS (
        SELECT FLDCODE, MAX(BASEYYMM) AS MAX_BASEYYMM
        FROM CTE_GROUPED
        GROUP BY FLDCODE
    ),
    CTE_FINAL AS (
        SELECT
            G.FLDCODE, G.ITEM, G.CATEGORY, G.BUDGET,
            SUM(H.COSTAMT_MONTH_SUM) AS ACTUAL
        FROM CTE_GROUPED G
        JOIN CTE_LATEST L ON L.FLDCODE = G.FLDCODE AND L.MAX_BASEYYMM = G.BASEYYMM
        JOIN CTE_GROUPED H ON H.FLDCODE = G.FLDCODE AND H.ITEM = G.ITEM AND H.BASEYYMM <= G.BASEYYMM
        GROUP BY G.FLDCODE, G.ITEM, G.CATEGORY, G.BUDGET
    )
    SELECT
        F.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = F.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(F.FLDCODE) AS PROJECT_NAME,
        F.CATEGORY AS CATEGORY,
        F.ITEM AS ITEM,
        F.BUDGET AS BUDGET,
        F.ACTUAL AS ACTUAL,
        DECODE(F.ITEM, 'Outsourcing', 1, 'Common', 2, 'Expense 1', 3, 'Expense 2', 4, 'Contingency', 5, 6) AS SORT_ORDER
    FROM CTE_FINAL F
    ORDER BY PROJECT_NAME, SORT_ORDER`,
  },

  "dashboard_pd_costestimation_1q.jsp": {
    // Cost Rate — CHỈ mục "Execution Budget" (실행예산원가율). Bidding và Estimated Completion chưa có
    // nguồn PIMS đáng tin cậy đã xác minh (xem MaTran_NguonDuLieu_Dashboard_PIMS_DECV_v4.xlsx #12/#14) —
    // vẫn giữ nhập tay. Nguồn: CDTB_PFMSUM_VINA join CDTB_PFMCHGSEQ lọc BDGTTYPECODE='1' (Execution
    // Budget - xác minh qua COMPRSN/TITLE1/TITLE2 thực tế, khác '0'=Initial/Bidding và '2'=Change/test)
    // và APPRSTSCODE='40' (đã duyệt), lấy PFMCHGSEQ mới nhất còn thoả điều kiện.
    sql: `WITH EXEC_BUDGET_SEQ AS (
        SELECT FLDCODE, MAX(PFMCHGSEQ) AS PFMCHGSEQ
        FROM CDTB_PFMCHGSEQ
        WHERE BDGTTYPECODE = '1' AND APPRSTSCODE = '40'
        GROUP BY FLDCODE
    )
    SELECT
        P.FLDCODE AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = P.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(P.FLDCODE) AS PROJECT_NAME,
        MAX(CASE WHEN P.STNDCODE = 'ZYA' THEN P.BDGTAMT END) AS COST_AMOUNT,
        MAX(CASE WHEN P.STNDCODE = 'ZZL' THEN P.BDGTAMT END) AS CONTRACT_AMOUNT
    FROM CDTB_PFMSUM_VINA P
    JOIN EXEC_BUDGET_SEQ S ON S.FLDCODE = P.FLDCODE AND S.PFMCHGSEQ = P.PFMCHGSEQ
    WHERE P.CURCODE = 'USD' AND P.STNDCODE IN ('ZYA', 'ZZL')
    GROUP BY P.FLDCODE
    ORDER BY PROJECT_NAME`,
  },

  "dashboard_pd_milestones_1q.jsp": {
    sql: `SELECT
        H.FLDCODE                                         AS FLDCODE,
        (SELECT MAX(FM.ACNT_FLDCODE) FROM CBTB_FLD_MAPPING FM WHERE FM.FLDCODE = H.FLDCODE) AS SITE_CODE,
        FUN_GET_FLDNAME(H.FLDCODE)                        AS PROJECT_NAME,
        FUN_GET_CA_REFFPF('37', H.HISTTYPEDVSCODE, 'KR')  AS LABEL,
        CAST(NULL AS VARCHAR2(7))                         AS PLAN_START,
        CAST(NULL AS VARCHAR2(7))                         AS PLAN_END,
        CASE WHEN REGEXP_LIKE(H.HISTDATE, '^[0-9]{8}$') THEN SUBSTR(H.HISTDATE, 1, 4) || '-' || SUBSTR(H.HISTDATE, 5, 2) END AS ACTUAL_START,
        CASE WHEN REGEXP_LIKE(H.HISTDATE, '^[0-9]{8}$') THEN SUBSTR(H.HISTDATE, 1, 4) || '-' || SUBSTR(H.HISTDATE, 5, 2) END AS ACTUAL_END,
        ROW_NUMBER() OVER (PARTITION BY H.FLDCODE ORDER BY H.HISTDATE)          AS SORT_ORDER
    FROM CBTB_CONSTHISTORY H
    ORDER BY PROJECT_NAME, H.HISTDATE`,
  },

  "dashboard_common_siterate_1q.jsp": {
    sql: `SELECT
        A.FLDCODE,
        A.CTRTCURCODE,
        A.LCLCURCODE,
        A.BASECURCODE,
        A.RATEUSD AS RATE_USD,
        A.RATEKRW AS RATE_KRW
    FROM CBTB_CTRTSUMM A
    WHERE UPPER(A.FLDCODE) = UPPER(:site_code)`,
    binds: (params) => ({ site_code: params.site_code ?? "" }),
  },

  "dashboard_common_exchangerate_1q.jsp": {
    sql: `SELECT
        R.EXCHANGE_TYPE,
        R.BASEMONEY,
        R.CHGMONEY,
        R.YYMM,
        R.CHGRATIO AS RATE
    FROM CHTB_EXCHANGE_RATIO R
    WHERE R.EXCHANGE_TYPE = '.'
        AND R.BASEMONEY IN ('VND', 'USD', 'JYP', 'KRW')
        AND R.CHGMONEY IN ('VND', 'USD', 'JYP', 'KRW')
        AND R.YYMM = (SELECT MAX(YYMM) FROM CHTB_EXCHANGE_RATIO WHERE EXCHANGE_TYPE = '.' AND YYMM <= :as_of)
    ORDER BY R.CHGMONEY`,
    binds: (params) => ({ as_of: params.as_of || currentYYYYMM() }),
  },
};
