// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pims-dashboard/Current.tsx": () => import("../components/mockups/pims-dashboard/Current.tsx"),
  "./components/mockups/pims-dashboard/components/CashFlowChart.tsx": () => import("../components/mockups/pims-dashboard/components/CashFlowChart.tsx"),
  "./components/mockups/pims-dashboard/components/CommentPanel.tsx": () => import("../components/mockups/pims-dashboard/components/CommentPanel.tsx"),
  "./components/mockups/pims-dashboard/components/Dashboard.tsx": () => import("../components/mockups/pims-dashboard/components/Dashboard.tsx"),
  "./components/mockups/pims-dashboard/components/DashboardHeader.tsx": () => import("../components/mockups/pims-dashboard/components/DashboardHeader.tsx"),
  "./components/mockups/pims-dashboard/components/KPICards.tsx": () => import("../components/mockups/pims-dashboard/components/KPICards.tsx"),
  "./components/mockups/pims-dashboard/components/OrderStatus.tsx": () => import("../components/mockups/pims-dashboard/components/OrderStatus.tsx"),
  "./components/mockups/pims-dashboard/components/PerformanceTable.tsx": () => import("../components/mockups/pims-dashboard/components/PerformanceTable.tsx"),
  "./components/mockups/pims-dashboard/components/ProfitChart.tsx": () => import("../components/mockups/pims-dashboard/components/ProfitChart.tsx"),
  "./components/mockups/pims-dashboard/components/SalesChart.tsx": () => import("../components/mockups/pims-dashboard/components/SalesChart.tsx"),
  "./components/mockups/pims-dashboard/components/Sidebar.tsx": () => import("../components/mockups/pims-dashboard/components/Sidebar.tsx"),
  "./components/mockups/pims-dashboard/components/TopNav.tsx": () => import("../components/mockups/pims-dashboard/components/TopNav.tsx")
};
